export * from "./hero-section";
export * from "./admission-steps";
export * from "./landing-header";
export * from "./directions";
export * from "./direction-quiz";
export * from "./advantages";
export * from "./benefits";
export * from "./faq";
export * from "./legal-basis";
